### Semana 1: MATRIZ. MATRICES ELEMENTALES. OPERACIONES CON MATRICES. MATRIZ ESCALONADA. INVERSA DE UNA MATRIZ. DETERMINANTE

In [2]:
import pandas as pd
import numpy as np

Lea  la  base  de  datos  y  tomando  solo  las  variables  numéricas,  convierta  esta  última  en  una 
matriz.

Para leer la data que se encuentra separada por puntos y comas agregue el parámetro 
``sep=”;”`` a la función ``pd.read_csv( )``). 

In [20]:
data = pd.read_csv("banca.csv", sep=";")
data.select_dtypes(["float64", "int64"])

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56       261         1    999         0           1.1          93.994   
1       57       149         1    999         0           1.1          93.994   
2       37       226         1    999         0           1.1          93.994   
3       40       151         1    999         0           1.1          93.994   
4       56       307         1    999         0           1.1          93.994   
...    ...       ...       ...    ...       ...           ...             ...   
41183   73       334         1    999         0          -1.1          94.767   
41184   46       383         1    999         0          -1.1          94.767   
41185   56       189         2    999         0          -1.1          94.767   
41186   44       442         1    999         0          -1.1          94.767   
41187   74       239         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  
0              -36.4      4.857       5191.0  
1              -36.4      4.857       5191.0  
2              -36.4      4.857       5191.0  
3              -36.4      4.857       5191.0  
4              -36.4      4.857       5191.0  
...              ...        ...          ...  
41183          -50.8      1.028       4963.6  
41184          -50.8      1.028       4963.6  
41185          -50.8      1.028       4963.6  
41186          -50.8      1.028       4963.6  
41187          -50.8      1.028       4963.6  

[41188 rows x 10 columns]

Convirtiendo mi **DataFrame** númerico en un **array**

In [17]:
arrayBanca = data.select_dtypes(["float64", "int64"]).to_numpy()
arrayBanca

array([[ 5.6000e+01,  2.6100e+02,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       [ 5.7000e+01,  1.4900e+02,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       [ 3.7000e+01,  2.2600e+02,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       ...,
       [ 5.6000e+01,  1.8900e+02,  2.0000e+00, ..., -5.0800e+01,
         1.0280e+00,  4.9636e+03],
       [ 4.4000e+01,  4.4200e+02,  1.0000e+00, ..., -5.0800e+01,
         1.0280e+00,  4.9636e+03],
       [ 7.4000e+01,  2.3900e+02,  3.0000e+00, ..., -5.0800e+01,
         1.0280e+00,  4.9636e+03]])

Viendo las dimensiones de mi **array**

In [21]:
arrayBanca.shape

(41188, 10)

Calcule el vector de **medias**

In [19]:
Medias = np.mean(arrayBanca, axis=0)
Medias

array([ 4.00240604e+01,  2.58285010e+02,  2.56759250e+00,  9.62475454e+02,
        1.72962999e-01,  8.18855006e-02,  9.35756644e+01, -4.05026003e+01,
        3.62129081e+00,  5.16703591e+03])

Calcule **la resta de la matriz** con el vector de **medias**

In [22]:
Resta = arrayBanca - Medias
Resta

array([[  15.97593959,    2.7149898 ,   -1.5675925 , ...,    4.10260027,
           1.23570919,   23.96408906],
       [  16.97593959, -109.2850102 ,   -1.5675925 , ...,    4.10260027,
           1.23570919,   23.96408906],
       [  -3.02406041,  -32.2850102 ,   -1.5675925 , ...,    4.10260027,
           1.23570919,   23.96408906],
       ...,
       [  15.97593959,  -69.2850102 ,   -0.5675925 , ...,  -10.29739973,
          -2.59329081, -203.43591094],
       [   3.97593959,  183.7149898 ,   -1.5675925 , ...,  -10.29739973,
          -2.59329081, -203.43591094],
       [  33.97593959,  -19.2850102 ,    0.4324075 , ...,  -10.29739973,
          -2.59329081, -203.43591094]])

Calcule la matriz de **covarianza**

In [23]:
Covarianza = np.cov(arrayBanca, rowvar=False)
Covarianza

array([[ 1.08602451e+02, -2.33914694e+00,  1.32602905e-01,
        -6.69453996e+01,  1.25660856e-01, -6.06862678e-03,
         5.16790762e-03,  6.23980083e+00,  1.94622473e-01,
        -1.33461599e+01],
       [-2.33914694e+00,  6.72257289e+04, -5.14948884e+01,
        -2.30568302e+03,  2.64851986e+00, -1.13918021e+01,
         7.97271590e-01, -9.80741194e+00, -1.47938307e+01,
        -8.37439866e+02],
       [ 1.32602905e-01, -5.14948884e+01,  7.67297503e+00,
         2.72249214e+01, -1.08493675e-01,  6.56017208e-01,
         2.04971433e-01, -1.76060671e-01,  6.49236419e-01,
         2.88388223e+01],
       [-6.69453996e+01, -2.30568302e+03,  2.72249214e+01,
         3.49356873e+04, -5.43464475e+01,  7.95748230e+01,
         8.53513249e+00, -7.90166771e+01,  9.62508736e+01,
         5.03187748e+03],
       [ 1.25660856e-01,  2.64851986e+00, -1.08493675e-01,
        -5.43464475e+01,  2.44927079e-01, -3.26917530e-01,
        -5.81903503e-02, -1.16669718e-01, -3.90128214e-01,
        -1.

Verificando la cantidad de columnas y filas que tiene mi variable ``Covarianza``

In [24]:
Covarianza.shape

(10, 10)

Nos piden calcular la matriz inversa del **array** ``arrayBanca`` 
 - Primero se validará si tiene **determinante**, para realizar lo solicitado

In [25]:
Determinante = np.linalg.det(Covarianza)
Determinante

27052276386628.715

Al ver que tiene determinante, se procedera a calcular la **matriz inversa**

In [26]:
Inversa = np.linalg.inv(Covarianza)
Inversa

array([[ 9.38173198e-03,  3.34861347e-07, -4.19763601e-04,
         1.36121285e-06, -3.83502917e-03,  5.91771204e-03,
        -3.34866075e-03, -2.57771661e-03, -6.23700615e-03,
         6.72917534e-05],
       [ 3.34861347e-07,  1.50158934e-05,  9.62870679e-05,
         9.83273819e-07,  2.49779398e-04,  6.70782611e-06,
        -1.19291115e-04,  2.30610883e-05, -1.93072125e-04,
         6.38651062e-06],
       [-4.19763601e-04,  9.62870679e-05,  1.35335551e-01,
         1.09911594e-05,  1.42838208e-02, -6.63710866e-02,
        -8.70631753e-02, -4.79336291e-03,  1.41186158e-01,
        -2.19436697e-03],
       [ 1.36121285e-06,  9.83273819e-07,  1.09911594e-05,
         4.62235336e-05,  9.18864731e-03,  2.31031936e-04,
         1.76824294e-03,  2.62003352e-04, -4.10047095e-04,
        -1.72357243e-05],
       [-3.83502917e-03,  2.49779398e-04,  1.42838208e-02,
         9.18864731e-03,  7.33548730e+00, -3.74523111e-01,
         4.38774276e-01,  6.87595024e-02, -7.94986119e-02,
         2.

Por teoría : ``𝐴𝐴−1 = 𝐴−1 𝐴 = 𝐼𝑛``, entonces : 

In [27]:
MatrizIdentidad = np.dot(Covarianza, Inversa)
MatrizIdentidad

array([[ 1.00000000e+00,  5.47099191e-21,  2.66908403e-18,
        -1.71729458e-19, -3.00646598e-16, -9.03938221e-17,
        -5.82113096e-17,  2.51083106e-17,  1.72138955e-16,
        -1.44743897e-17],
       [ 1.10696406e-17,  1.00000000e+00,  7.80533129e-16,
         7.89251199e-18,  3.93705104e-15, -1.56431942e-14,
        -2.55370673e-14,  2.45406346e-16, -2.45697645e-16,
         2.41898393e-16],
       [ 3.87236333e-17, -8.34722037e-20,  1.00000000e+00,
        -2.36626904e-18, -7.96234455e-15,  8.67428692e-15,
         1.94604348e-14,  1.57324433e-15,  3.02404247e-14,
        -5.17067573e-16],
       [ 4.99789870e-17, -5.58212555e-18, -1.99478655e-15,
         1.00000000e+00, -6.59112051e-15, -1.12025056e-13,
         1.65759945e-13,  1.24219674e-14, -2.11531815e-13,
         6.59572439e-15],
       [ 5.29788523e-19,  8.33242280e-20,  4.03028313e-18,
        -3.27512491e-19,  1.00000000e+00, -1.06927196e-15,
         4.11680843e-15,  4.33155304e-16, -6.77487349e-15,
         5.

Se observa que la diagonal dentro del objeto ``MatrizIdentidad`` tiene elementos iguales a 1

Utilice un bucle ``for`` y multiplique cada fila de la matriz resta con la matriz inversa y la transpuesta de la fila de la matriz resta

In [33]:
Valores = []
for i in range(0, Resta.shape[0]):
    valor = np.dot(np.dot(Resta[i], Inversa), Resta[i].T)
    Valores.append(valor)
Valores

[4.2553147049709645,
 4.764125246930477,
 2.381279181088577,
 2.417393396621837,
 4.273646383090635,
 2.4063976859000284,
 5.433900787076352,
 2.2323314097156297,
 5.128205236172264,
 5.374817223407346,
 2.889441569521484,
 4.675301631202798,
 3.8467208213594106,
 4.5491594393899035,
 2.7797253443471748,
 3.875203845344741,
 2.569353924105827,
 2.8369444148903833,
 3.022400667632836,
 2.319006450708526,
 4.17431647305916,
 3.9860023469346713,
 4.061075721539883,
 2.310243797067991,
 2.498292422219125,
 2.9896124459661504,
 5.647562336099415,
 2.2538328169790796,
 3.4292781822095817,
 4.109875852053841,
 2.496975520479913,
 5.3733463886666115,
 3.3526458007013225,
 3.759539696666658,
 3.793747295360704,
 4.048778161760983,
 2.801405224635995,
 32.51917874624516,
 3.5938733037617476,
 4.522433910528547,
 4.984682222018376,
 3.003043341010799,
 2.467412446804116,
 4.593451601951422,
 2.367227639529517,
 3.1261105456823506,
 6.331991571606109,
 2.3309664141322535,
 2.649807956744368,
 2.05

Importe la función ``mahalanobis`` de la librería ``scipy.spatial.distance``  (``from scipy.spatial.distance  import  mahalanobis``)

In [35]:
from scipy.spatial.distance  import  mahalanobis

Replique el producto matricial anterior para obtener los mismos resultados mediante ```mahalanobis``` ```(Fila de la matriz de datos, vector de medias, matriz de covarianza inversa)**2```

In [39]:
ValoresMahalanobis = []
for i in range(0, arrayBanca.shape[0]):
    x = mahalanobis(arrayBanca[i], Medias, Inversa) ** 2
    ValoresMahalanobis.append(x)
ValoresMahalanobis

[4.2553147049709645,
 4.764125246930477,
 2.3812791810885767,
 2.417393396621837,
 4.273646383090637,
 2.4063976859000284,
 5.433900787076353,
 2.23233140971563,
 5.128205236172263,
 5.374817223407345,
 2.889441569521485,
 4.675301631202798,
 3.8467208213594106,
 4.5491594393899035,
 2.779725344347175,
 3.8752038453447413,
 2.5693539241058274,
 2.8369444148903833,
 3.0224006676328354,
 2.319006450708526,
 4.174316473059162,
 3.986002346934672,
 4.061075721539883,
 2.3102437970679914,
 2.4982924222191247,
 2.9896124459661504,
 5.647562336099416,
 2.25383281697908,
 3.4292781822095826,
 4.10987585205384,
 2.4969755204799133,
 5.373346388666614,
 3.3526458007013233,
 3.759539696666658,
 3.7937472953607045,
 4.048778161760985,
 2.801405224635995,
 32.51917874624517,
 3.5938733037617476,
 4.522433910528548,
 4.984682222018376,
 3.0030433410108004,
 2.4674124468041163,
 4.593451601951425,
 2.3672276395295166,
 3.12611054568235,
 6.331991571606111,
 2.330966414132254,
 2.6498079567443686,
 2.

Agregamos esta última lista a nuestro **DataFrame númerico** 

In [46]:
DFMahalanobis = data.select_dtypes(["float64", "int64"])
DFMahalanobis["Mahalanobis"] = ValoresMahalanobis
DFMahalanobis

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56       261         1    999         0           1.1          93.994   
1       57       149         1    999         0           1.1          93.994   
2       37       226         1    999         0           1.1          93.994   
3       40       151         1    999         0           1.1          93.994   
4       56       307         1    999         0           1.1          93.994   
...    ...       ...       ...    ...       ...           ...             ...   
41183   73       334         1    999         0          -1.1          94.767   
41184   46       383         1    999         0          -1.1          94.767   
41185   56       189         2    999         0          -1.1          94.767   
41186   44       442         1    999         0          -1.1          94.767   
41187   74       239         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  Mahalanobis  
0              -36.4      4.857       5191.0     4.255315  
1              -36.4      4.857       5191.0     4.764125  
2              -36.4      4.857       5191.0     2.381279  
3              -36.4      4.857       5191.0     2.417393  
4              -36.4      4.857       5191.0     4.273646  
...              ...        ...          ...          ...  
41183          -50.8      1.028       4963.6    63.591979  
41184          -50.8      1.028       4963.6    52.691288  
41185          -50.8      1.028       4963.6    55.386806  
41186          -50.8      1.028       4963.6    52.541504  
41187          -50.8      1.028       4963.6    61.169682  

[41188 rows x 11 columns]

Con base a esto, elimine aquellos registros cuyas distancias de Mahalanobis sean mayores a 100
 - Primero nos quedamos con aquellos registros menores a 100

In [47]:
DFMahalanobis = DFMahalanobis[DFMahalanobis["Mahalanobis"] < 100]
DFMahalanobis

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56       261         1    999         0           1.1          93.994   
1       57       149         1    999         0           1.1          93.994   
2       37       226         1    999         0           1.1          93.994   
3       40       151         1    999         0           1.1          93.994   
4       56       307         1    999         0           1.1          93.994   
...    ...       ...       ...    ...       ...           ...             ...   
41183   73       334         1    999         0          -1.1          94.767   
41184   46       383         1    999         0          -1.1          94.767   
41185   56       189         2    999         0          -1.1          94.767   
41186   44       442         1    999         0          -1.1          94.767   
41187   74       239         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  Mahalanobis  
0              -36.4      4.857       5191.0     4.255315  
1              -36.4      4.857       5191.0     4.764125  
2              -36.4      4.857       5191.0     2.381279  
3              -36.4      4.857       5191.0     2.417393  
4              -36.4      4.857       5191.0     4.273646  
...              ...        ...          ...          ...  
41183          -50.8      1.028       4963.6    63.591979  
41184          -50.8      1.028       4963.6    52.691288  
41185          -50.8      1.028       4963.6    55.386806  
41186          -50.8      1.028       4963.6    52.541504  
41187          -50.8      1.028       4963.6    61.169682  

[41094 rows x 11 columns]

Eliminamos la columna ``Mahalanobis``

In [48]:
DFMahalanobis = DFMahalanobis.drop(["Mahalanobis"], axis=1)
DFMahalanobis

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56       261         1    999         0           1.1          93.994   
1       57       149         1    999         0           1.1          93.994   
2       37       226         1    999         0           1.1          93.994   
3       40       151         1    999         0           1.1          93.994   
4       56       307         1    999         0           1.1          93.994   
...    ...       ...       ...    ...       ...           ...             ...   
41183   73       334         1    999         0          -1.1          94.767   
41184   46       383         1    999         0          -1.1          94.767   
41185   56       189         2    999         0          -1.1          94.767   
41186   44       442         1    999         0          -1.1          94.767   
41187   74       239         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  
0              -36.4      4.857       5191.0  
1              -36.4      4.857       5191.0  
2              -36.4      4.857       5191.0  
3              -36.4      4.857       5191.0  
4              -36.4      4.857       5191.0  
...              ...        ...          ...  
41183          -50.8      1.028       4963.6  
41184          -50.8      1.028       4963.6  
41185          -50.8      1.028       4963.6  
41186          -50.8      1.028       4963.6  
41187          -50.8      1.028       4963.6  

[41094 rows x 10 columns]